# Experiment 2
## Numerical Python (NUMPY)

### Normalization Problem
#### In this problem, it adjust the data by centering which means subtracting the mean from the data and scaling means dividing it to deviation.
#### I use .mean and .std in calculating the mean and standard deviation

In [2]:
import numpy as np

In [3]:
# Create a random 5x5 ndarray and store it to variable X
X = np.random.rand(5, 5)

In [4]:
# Normalize X
Xnormal = (X - X.mean()) / X.std()

In [5]:
# Display the normalized array
print(Xnormal)

[[ 1.29736732 -0.00374791 -0.06785726  1.68763919 -0.79220166]
 [-0.06299544 -0.44637501 -1.12340125 -1.07883481  0.10758626]
 [-0.6008941  -0.10567363  1.78478659 -0.71713765 -0.879398  ]
 [-0.43288934 -0.0955523  -1.36728729 -0.60110345  1.88814733]
 [-0.75001206  0.43498447  1.04119944  1.87914941 -0.99549886]]


In [23]:
# Save the normalized array
np.save('X_normalized.npy', Xnormal)

## Divisible by 3 Problem
#### In this problem, each elements in the 10x10 ndarray represents the square of the first 100 positive integers.
#### the goal of this problem is to find all the elements that is divisible by 3.

In [6]:
import numpy as np

In [8]:
# create a 10x10 ndarray which are the squares of the first 100 positive integers
A = np.arange(1, 101).reshape(10, 10) ** 2

In [10]:
# Know the elements that is divisible by 3
div = A[A % 3 == 0]

In [12]:
#display the array of elements that is divisible by 3
print(div)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [14]:
# Save the result
np.save('div_by_3.npy', div)